SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `JKM` ;


CREATE SCHEMA IF NOT EXISTS `JKM` DEFAULT CHARACTER SET utf8 ;
USE `JKM`;

-- -----------------------------------------------------
-- Table `JKM`.`PERSON_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`PERSON_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`PERSON_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `JKM`.`STATUS_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`STATUS_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`STATUS_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `STATUS_NAME` VARCHAR(50) NOT NULL ,
  `CREATED_BY` VARCHAR(45) NOT NULL ,
  `CREATED_ON` DATETIME NOT NULL ,
  `MODIFIED_BY` VARCHAR(45) NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`STATUS_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`STATUS_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`STATUS_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `STATUS_TYPE_ID` INT NOT NULL ,
  `CUSTOMER_STATUS` VARCHAR(60) NOT NULL ,
  `AGENT_STATUS` VARCHAR(60) NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `STATUS_ID_STATUS_TYPE_ID_REF`
    FOREIGN KEY (`STATUS_TYPE_ID` )
    REFERENCES `JKM`.`STATUS_TYPE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `STATUS_ID_STATUS_TYPE_ID_REF_IDX` ON `JKM`.`STATUS_REF` (`STATUS_TYPE_ID` ASC) ;

-- -----------------------------------------------------
-- Table `JKM`.`OPERATOR_ACCOUNT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`OPERATOR_ACCOUNT` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`OPERATOR_ACCOUNT` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `ACCOUNT_CD` VARCHAR(30) NOT NULL COMMENT 'REPRESENTS ACCOUNT CODE OF THE OPERATOR.' ,
  `USER_NM` VARCHAR(25) NOT NULL ,
  `PWD` VARCHAR(20) NOT NULL ,
  `STATUS_ID` INT NOT NULL ,
  `DISPLAY_NM` VARCHAR(45) NULL ,
  `MASTER_ACCOUNT_CD` VARCHAR(45) NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_OPERATOR_STTS_ID`
    FOREIGN KEY (`STATUS_ID` )
    REFERENCES `JKM`.`STATUS_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `OPERATOR_STTS_ID_FK_IDX` ON `JKM`.`OPERATOR_ACCOUNT` (`STATUS_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`OPERATOR_INFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`OPERATOR_INFO` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`OPERATOR_INFO` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `OPERATOR_ID` INT NOT NULL ,
  `OPERATOR_CD` VARCHAR(20) NULL ,
  `PERSON_TYP_ID` INT NOT NULL COMMENT 'e.g: BUSINESS, INDIVIDUAL' ,
  `FIRST_NM` VARCHAR(30) NOT NULL ,
  `MIDDLE_NM` VARCHAR(30) NULL ,
  `LAST_NM` VARCHAR(30) NOT NULL ,
  `BUSINESS_NM` VARCHAR(60) NULL ,
  `GENDER_TYP` VARCHAR(10) NULL ,
  `BIRTH_DT` DATE NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(20) NULL ,
  `MODIFIED_BY` VARCHAR(20) NULL ,
  `STATE_ID` INT NULL ,
  `CITY_ID` INT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_OPERATOR_PERSON_TYPE_ID`
    FOREIGN KEY (`PERSON_TYP_ID` )
    REFERENCES `JKM`.`PERSON_TYPE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OPERATOR_ACCOUNT_ID`
    FOREIGN KEY (`ID` )
    REFERENCES `JKM`.`OPERATOR_ACCOUNT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `PERSON_TYPE_ID_IDX` ON `JKM`.`OPERATOR_INFO` (`PERSON_TYP_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`PHONE_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`PHONE_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`PHONE_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`OPERATOR_PHONE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`OPERATOR_PHONE` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`OPERATOR_PHONE` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `OPERATOR_INFO_ID` INT NOT NULL ,
  `PHONE_TYP_ID` INT NOT NULL ,
  `AREA_CD` VARCHAR(10) NULL ,
  `PHONE_NO` VARCHAR(15) NOT NULL ,
  `PHONE_EXT` VARCHAR(10) NULL ,
  `COMMENTS_TXT` VARCHAR(150) NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_OPERATOR_INFO_ID`
    FOREIGN KEY (`OPERATOR_INFO_ID` )
    REFERENCES `JKM`.`OPERATOR_INFO` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OPERATOR_PHONE_TYP_ID`
    FOREIGN KEY (`PHONE_TYP_ID` )
    REFERENCES `JKM`.`PHONE_TYPE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `CUST_TEL_TEL_TYP_REF_FK_IDX` ON `JKM`.`OPERATOR_PHONE` (`PHONE_TYP_ID` ASC) ;

CREATE INDEX `FK_OPERATOR_INFO_ID_IDX` ON `JKM`.`OPERATOR_PHONE` (`OPERATOR_INFO_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`NATIONAL_HOLIDAY_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`NATIONAL_HOLIDAY_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`NATIONAL_HOLIDAY_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `HOLIDAY_DT` DATE NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `YEAR` YEAR NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `JKM`.`OBJECT_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`OBJECT_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`OBJECT_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`PARAMETER_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`PARAMETER_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`PARAMETER_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `SORT_ORDER` INT NOT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`PARAMETER_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`PARAMETER_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`PARAMETER_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `PARAMETER_TYP_ID` INT NOT NULL ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(100) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_PARAM_PARAMTYP_ID`
    FOREIGN KEY (`PARAMETER_TYP_ID` )
    REFERENCES `JKM`.`PARAMETER_TYPE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `PARAM_REF_PARAM_TYP_REF_FK_IDX` ON `JKM`.`PARAMETER_REF` (`PARAMETER_TYP_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`PROMOTION_GROUP_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`PROMOTION_GROUP_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`PROMOTION_GROUP_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NULL ,
  `PROMO_GRP_TYPE` CHAR(1)  NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(45) NULL ,
  `MODIFIED_BY` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `CODE_UNIQUE` ON `JKM`.`PROMOTION_GROUP_REF` (`CODE` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`PROMOTION_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`PROMOTION_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`PROMOTION_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

CREATE UNIQUE INDEX `CODE_UNIQUE` ON `JKM`.`PROMOTION_TYPE_REF` (`CODE` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`PROMOTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`PROMOTION` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`PROMOTION` (
  `PROMOTION_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `EFF_BEGIN_DT` DATE NOT NULL ,
  `EFF_END_DT` DATE NOT NULL ,
  `PROMOTION_CD` VARCHAR(30) NOT NULL ,
  `PROMO_TYPE_ID` INT(11) NOT NULL ,
  `PROMO_GROUP_ID` INT(11) NOT NULL ,
  `PROMOTION_VAL` DECIMAL(10,2) NOT NULL ,
  `PROMOTION_DSC` VARCHAR(200) NULL ,
  `SORT_ORDER_NO` INT(11) NULL DEFAULT NULL ,
  `TOTAL_USED` INT(11) NULL ,
  `UPPER_LIMIT` INT(11) NULL ,
  `STATUS_ID` INT(11) NULL ,
  PRIMARY KEY (`PROMOTION_ID`) ,
  CONSTRAINT `PROMOTION_PROMO_GRP_REF_FK`
    FOREIGN KEY (`PROMO_GROUP_ID` )
    REFERENCES `JKM`.`PROMOTION_GROUP_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PROMOTION_PROMOTYP_REF_FK`
    FOREIGN KEY (`PROMO_TYPE_ID` )
    REFERENCES `JKM`.`PROMOTION_TYPE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PROMO_STATUS_STATUS_REF_FK`
    FOREIGN KEY (`STATUS_ID` )
    REFERENCES `JKM`.`STATUS_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `PROMOTION_PROMOTYP_REF_FK_IDX` ON `JKM`.`PROMOTION` (`PROMO_TYPE_ID` ASC) ;

CREATE INDEX `PROMOTION_PROMO_GRP_REF_FK_IDX` ON `JKM`.`PROMOTION` (`PROMO_GROUP_ID` ASC) ;

CREATE INDEX `PROMO_STATUS_STATUS_REF_FK_IDX` ON `JKM`.`PROMOTION` (`STATUS_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`CUSTOMER_PROMOTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`CUSTOMER_PROMOTION` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`CUSTOMER_PROMOTION` (
  `PROMO_DETAIL_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `MOVE_INFO_ID` INT(11) NOT NULL ,
  `PROMOTION_ID` INT(11) NOT NULL ,
  `PROMOTION_AMT` DECIMAL(10,2) NULL DEFAULT NULL ,
  `PROMOTION_PCT` INT(11) NULL DEFAULT NULL ,
  `PROMO_EXP_DSC` VARCHAR(100) NULL DEFAULT NULL ,
  `CREATED_BY` VARCHAR(20) NOT NULL ,
  `CREATED_ON` DATETIME NOT NULL ,
  `CHANGED_BY` VARCHAR(20) NOT NULL ,
  `CHANGED_ON` DATETIME NOT NULL ,
  PRIMARY KEY (`PROMO_DETAIL_ID`) ,
  CONSTRAINT `PROMO_DETAIL_PROMOTION_FK`
    FOREIGN KEY (`PROMOTION_ID` )
    REFERENCES `JKM`.`PROMOTION` (`PROMOTION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `PROMO_DETAIL_PROMOTION_FK_IDX` ON `JKM`.`CUSTOMER_PROMOTION` (`PROMOTION_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`VEHICLE_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`VEHICLE_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`VEHICLE_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `TYPE` VARCHAR(10) NULL COMMENT 'Can be BUS or CAR etc' ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`ADDRESS_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`ADDRESS_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`ADDRESS_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`FACILITY_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`FACILITY_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`FACILITY_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`STATE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`STATE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`STATE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`STATE_HOLIDAY_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`STATE_HOLIDAY_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`STATE_HOLIDAY_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `HOLIDAY_DT` DATE NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NULL ,
  `YEAR` YEAR NOT NULL ,
  `STATE_ID` INT NOT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_STATE_HOLIDAY_STATE_ID`
    FOREIGN KEY (`STATE_ID` )
    REFERENCES `JKM`.`STATE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `STATE_ID_IDX` ON `JKM`.`STATE_HOLIDAY_REF` (`STATE_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`CITY_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`CITY_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`CITY_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `STATE_ID` INT NOT NULL ,
  `ACTIVE_FLG` CHAR(1) NOT NULL ,
  `ZIP_CD` VARCHAR(10) NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` TIMESTAMP NULL ,
  `MODIFIED_ON` TIMESTAMP NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `STATE_ID`
    FOREIGN KEY (`STATE_ID` )
    REFERENCES `JKM`.`STATE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `STATE_ID_IDX` ON `JKM`.`CITY_REF` (`STATE_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`VEHICLE_PERMIT_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`VEHICLE_PERMIT_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`VEHICLE_PERMIT_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL COMMENT 'NATIONAL, STATE' ,
  `DESCRIPTION` VARCHAR(100) NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`VEHICLE_SERVICE_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`VEHICLE_SERVICE_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`VEHICLE_SERVICE_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL COMMENT 'Willing to service NATIONAL Level or State Level' ,
  `DESCRIPTION` VARCHAR(100) NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  `VEHICLE_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `VEHILE_SERICE_VEHICKE_ID_FK`
    FOREIGN KEY (`ID` )
    REFERENCES `JKM`.`VEHICLE_INFO` (`VEHICLE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`SEATER_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`SEATER_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`SEATER_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(45) NULL ,
  `MODIFIED_BY` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`VEHICLE_NAME_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`VEHICLE_NAME_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`VEHICLE_NAME_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`VEHICLE_INFO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`VEHICLE_INFO` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`VEHICLE_INFO` (
  `VEHICLE_ID` INT NOT NULL AUTO_INCREMENT ,
  `OPERATOR_ACCT_ID` INT NOT NULL ,
  `CUSTOM_NAME` VARCHAR(60) NULL ,
  `VEHICLE_NM_ID` INT NOT NULL ,
  `SEATER_ID` INT NULL ,
  `VEHICLE_COLOR` VARCHAR(25) NULL ,
  `VEHICLE_MODEL` VARCHAR(25) NULL ,
  `VEHICLE_YR` INT NULL ,
  `VEHICLE_ODOMETER` INT NULL ,
  `VEHICLE_TYPE_ID` INT NOT NULL ,
  `REGN_NO` VARCHAR(45) NULL ,
  `PERMIT_TYPE_ID` INT NULL ,
  `INSURANCE_COMP_NM` VARCHAR(60) NULL ,
  `POLICY_NO` VARCHAR(25) NULL ,
  `POLICY_EFF_FRM` DATETIME NULL ,
  `POLICY_EFF_TO` DATETIME NULL ,
  `FITNESS_CERT_NO` VARCHAR(25) NULL ,
  `FITNESS_ISSUE_DT` DATETIME NULL ,
  `FITNESS_EXP_DT` DATETIME NULL ,
  `POLLUTION_EFF_FRM` DATETIME NULL ,
  `POLLUTION_EFF_TO` DATETIME NULL ,
  `SERVICE_TYPE_ID` INT NULL ,
  `BASE_CITY_ID` INT NULL ,
  `BASE_STATE_ID` INT NULL ,
  `ALL_INDIA_SERVICE_FLG` TINYINT(1) NULL ,
  `REG_FROM` DATE NOT NULL ,
  `REG_TO` DATE NOT NULL ,
  `VEHICLE_STATUS_ID` INT NOT NULL ,
  `CREATED_BY` VARCHAR(25) NOT NULL ,
  `CREATED_ON` DATETIME NOT NULL ,
  `CHANGED_BY` VARCHAR(25) NULL ,
  `CHANGED_ON` DATETIME NULL ,
  PRIMARY KEY (`VEHICLE_ID`) ,
  CONSTRAINT `FK_OPERATOR_ACCOUNT_ID_01`
    FOREIGN KEY (`OPERATOR_ACCT_ID` )
    REFERENCES `JKM`.`OPERATOR_ACCOUNT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VEH_TYP_ID_02`
    FOREIGN KEY (`VEHICLE_TYPE_ID` )
    REFERENCES `JKM`.`VEHICLE_TYPE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VEH_PERMIT_TYP_ID_03`
    FOREIGN KEY (`PERMIT_TYPE_ID` )
    REFERENCES `JKM`.`VEHICLE_PERMIT_TYPE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VEH_SERVICE_TYP_ID_04`
    FOREIGN KEY (`SERVICE_TYPE_ID` )
    REFERENCES `JKM`.`VEHICLE_SERVICE_TYPE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VEH_STATE_REF_ID_05`
    FOREIGN KEY (`BASE_STATE_ID` )
    REFERENCES `JKM`.`STATE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VEH_CITY_REF_ID_06`
    FOREIGN KEY (`BASE_CITY_ID` )
    REFERENCES `JKM`.`CITY_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VEH_SEATER_REF_ID_07`
    FOREIGN KEY (`SEATER_ID` )
    REFERENCES `JKM`.`SEATER_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VEH_NM_REF_ID_08`
    FOREIGN KEY (`VEHICLE_NM_ID` )
    REFERENCES `JKM`.`VEHICLE_NAME_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VEH_STATUS_ID_REF_STATUS_REF`
    FOREIGN KEY (`VEHICLE_STATUS_ID` )
    REFERENCES `JKM`.`STATUS_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_OPERATOR_ACCOUNT_ID_01_IDX` ON `JKM`.`VEHICLE_INFO` (`OPERATOR_ACCT_ID` ASC) ;

CREATE INDEX `FK_VEH_TYPE_ID_02_IDX` ON `JKM`.`VEHICLE_INFO` (`VEHICLE_TYPE_ID` ASC) ;

CREATE UNIQUE INDEX `VEHICLE_ID_UNQ_08` ON `JKM`.`VEHICLE_INFO` (`VEHICLE_ID` ASC) ;

CREATE INDEX `FK_VEH_PERMIT_TYP_ID_03_IDX` ON `JKM`.`VEHICLE_INFO` (`PERMIT_TYPE_ID` ASC) ;

CREATE INDEX `FK_VEH_SERVICE_TYP_ID_04_IDX` ON `JKM`.`VEHICLE_INFO` (`SERVICE_TYPE_ID` ASC) ;

CREATE INDEX `FK_VEH_STATE_TYP_ID_05_IDX` ON `JKM`.`VEHICLE_INFO` (`BASE_STATE_ID` ASC) ;

CREATE INDEX `FK_VEH_CITY_REF_ID_06_IDX` ON `JKM`.`VEHICLE_INFO` (`BASE_CITY_ID` ASC) ;

CREATE INDEX `FK_VEH_SEATER_REF_ID_07_IDX` ON `JKM`.`VEHICLE_INFO` (`SEATER_ID` ASC) ;

CREATE INDEX `FK_VEH_NM_REF_ID_08_IDX` ON `JKM`.`VEHICLE_INFO` (`VEHICLE_NM_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`OPERATOR_ADDRESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`OPERATOR_ADDRESS` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`OPERATOR_ADDRESS` (
  `ADDRESS_ID` INT NOT NULL AUTO_INCREMENT ,
  `OPERATOR_ID` INT NOT NULL ,
  `ADDR_TYP_ID` INT NOT NULL ,
  `ADDR_LN1` VARCHAR(150) NOT NULL ,
  `ADDR_LN2` VARCHAR(100) NULL ,
  `CITY_ID` INT NOT NULL ,
  `STATE_ID` INT NOT NULL ,
  `ZIP_CD` VARCHAR(10) NULL ,
  `REGION` VARCHAR(20) NULL ,
  `LANDMARK` VARCHAR(150) NULL ,
  `COUNTRY` VARCHAR(20) NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ADDRESS_ID`) ,
  CONSTRAINT `FK_OPERATOR_ADDR_TYP_ID_01`
    FOREIGN KEY (`ADDR_TYP_ID` )
    REFERENCES `JKM`.`ADDRESS_TYPE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OPERATOR_INFO_ID_02`
    FOREIGN KEY (`OPERATOR_ID` )
    REFERENCES `JKM`.`OPERATOR_INFO` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OPERATOR_STATE_ID_03`
    FOREIGN KEY (`STATE_ID` )
    REFERENCES `JKM`.`STATE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OPERATOR_CITY_ID_04`
    FOREIGN KEY (`CITY_ID` )
    REFERENCES `JKM`.`CITY_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `ADDRESS_TYPE_ID_IDX` ON `JKM`.`OPERATOR_ADDRESS` (`ADDR_TYP_ID` ASC) ;

CREATE INDEX `OPERATOR_STATE_ID_FK_IDX` ON `JKM`.`OPERATOR_ADDRESS` (`STATE_ID` ASC) ;

CREATE INDEX `OPERATOR_CITY_ID_FK_IDX` ON `JKM`.`OPERATOR_ADDRESS` (`CITY_ID` ASC) ;

CREATE INDEX `FK_OPERATOR_INFO_ID_IDX` ON `JKM`.`OPERATOR_ADDRESS` (`OPERATOR_ID` ASC) ;

CREATE UNIQUE INDEX `ADDRESS_ID_UNIQUE` ON `JKM`.`OPERATOR_ADDRESS` (`ADDRESS_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`EMAIL_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`EMAIL_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`EMAIL_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`OPERATOR_EMAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`OPERATOR_EMAIL` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`OPERATOR_EMAIL` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `OPERATOR_INFO_ID` INT NOT NULL ,
  `EMAIL_TYP_ID` INT NOT NULL ,
  `EMAIL_ADDR` VARCHAR(75) NOT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_OPERATOR_INFO_ID_EMAIL_01`
    FOREIGN KEY (`OPERATOR_INFO_ID` )
    REFERENCES `JKM`.`OPERATOR_INFO` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OPERATOR_EMAIL_TYP_ID_02`
    FOREIGN KEY (`EMAIL_TYP_ID` )
    REFERENCES `JKM`.`EMAIL_TYPE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_OPERATOR_EMAIL_TYP_ID_IDX` ON `JKM`.`OPERATOR_EMAIL` (`EMAIL_TYP_ID` ASC) ;

CREATE INDEX `FK_OPERATOR_INFO_ID_IDX` ON `JKM`.`OPERATOR_EMAIL` (`OPERATOR_INFO_ID` ASC) ;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `JKM`.`OPERATOR_EMAIL` (`ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`PICK_DROP_LOCATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`PICK_DROP_LOCATIONS` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`PICK_DROP_LOCATIONS` (
  `PICKDROP_ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `ADDRESS` VARCHAR(100) NULL ,
  `LANDMARK` VARCHAR(100) NULL ,
  `CITY_ID` VARCHAR(45) NULL ,
  `STATE_ID` VARCHAR(45) NULL ,
  `AREA_NAME` VARCHAR(45) NULL ,
  `LOCATION_TYPE` VARCHAR(45) NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(45) NULL ,
  `MODIFIED_BY` VARCHAR(45) NULL ,
  `AMENITIES` VARCHAR(45) NULL ,
  PRIMARY KEY (`PICKDROP_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`FAX_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`FAX_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`FAX_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`OPERATOR_FAX`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`OPERATOR_FAX` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`OPERATOR_FAX` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `OPERATOR_ID` INT NOT NULL ,
  `FAX_TYP_ID` INT NOT NULL ,
  `FAX_NO` VARCHAR(15) NOT NULL ,
  `AREA_CD` VARCHAR(10) NULL ,
  `FAX_EXT` VARCHAR(10) NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(20) NULL ,
  `MODIFIED_BY` VARCHAR(20) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_OPERATOR_INFO_ID_FAX_01`
    FOREIGN KEY (`OPERATOR_ID` )
    REFERENCES `JKM`.`OPERATOR_INFO` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OPERATOR_FAX_TYP_ID_02`
    FOREIGN KEY (`FAX_TYP_ID` )
    REFERENCES `JKM`.`FAX_TYPE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_OPERATOR_FAX_TY_ID_IDX` ON `JKM`.`OPERATOR_FAX` (`FAX_TYP_ID` ASC) ;

CREATE INDEX `FK_OPERATOR_INFO_ID_IDX` ON `JKM`.`OPERATOR_FAX` (`OPERATOR_ID` ASC) ;

CREATE UNIQUE INDEX `ID_UNIQUE` ON `JKM`.`OPERATOR_FAX` (`ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`VEHICLE_AMENITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`VEHICLE_AMENITY` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`VEHICLE_AMENITY` (
  `VEHICLE_ID` INT NOT NULL ,
  `FACILITY_TYP_ID` INT NOT NULL ,
  `ID` INT NOT NULL AUTO_INCREMENT ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_VEHINFO_AMENITY`
    FOREIGN KEY (`VEHICLE_ID` )
    REFERENCES `JKM`.`VEHICLE_INFO` (`VEHICLE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VEHINFO_FACILITY_TYP`
    FOREIGN KEY (`FACILITY_TYP_ID` )
    REFERENCES `JKM`.`FACILITY_TYPE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `VEHICLE_FACILITY_VEHICLE_ID_FK_IDX` ON `JKM`.`VEHICLE_AMENITY` (`VEHICLE_ID` ASC) ;

CREATE INDEX `FK_VEHINFO_FACILITY_TYP_IDX` ON `JKM`.`VEHICLE_AMENITY` (`FACILITY_TYP_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`VEHICLE_PICTURE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`VEHICLE_PICTURE` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`VEHICLE_PICTURE` (
  `PICTURE_ID` INT NOT NULL AUTO_INCREMENT ,
  `VEHICLE_ID` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `DESCRIPTION` VARCHAR(60) NULL ,
  `LOCATION` VARCHAR(125) NULL ,
  `CREATED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`PICTURE_ID`) ,
  CONSTRAINT `VEHICLE_PICTURE_VEHICLE_ID_FK`
    FOREIGN KEY (`VEHICLE_ID` )
    REFERENCES `JKM`.`VEHICLE_INFO` (`VEHICLE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `VEHICLE_PICTURE_VEHICLE_ID_FK_IDX` ON `JKM`.`VEHICLE_PICTURE` (`VEHICLE_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`DOC_TYPE_REF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`DOC_TYPE_REF` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`DOC_TYPE_REF` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CODE` VARCHAR(20) NOT NULL ,
  `NAME` VARCHAR(60) NOT NULL ,
  `DESCRIPTION` VARCHAR(100) NOT NULL ,
  `SORT_ORDER` INT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`OPERATOR_REGN_DOC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`OPERATOR_REGN_DOC` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`OPERATOR_REGN_DOC` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `OPRERATOR_ID` INT NOT NULL ,
  `DOC_ID` INT NOT NULL ,
  `DOC_STATUS_ID` INT NOT NULL ,
  `VERIFIED_BY` VARCHAR(25) NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_OPERATOR_AC_OPERATOR_REGN_DOC`
    FOREIGN KEY (`DOC_ID` )
    REFERENCES `JKM`.`DOC_TYPE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OPERATOR_REGN_DOC_STATUS`
    FOREIGN KEY (`DOC_STATUS_ID` )
    REFERENCES `JKM`.`STATUS_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OPERATOR_ID`
    FOREIGN KEY (`OPRERATOR_ID` )
    REFERENCES `JKM`.`OPERATOR_INFO` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_OPERATOR_AC_OPERATOR_REGN_DOC_IDX` ON `JKM`.`OPERATOR_REGN_DOC` (`DOC_ID` ASC) ;

CREATE INDEX `FK_OPERATOR_REGN_DOC_STATUS_IDX` ON `JKM`.`OPERATOR_REGN_DOC` (`DOC_STATUS_ID` ASC) ;

CREATE INDEX `FK_OPERATOR_ID_IDX` ON `JKM`.`OPERATOR_REGN_DOC` (`OPRERATOR_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`OPERATOR_REGN_REQUEST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`OPERATOR_REGN_REQUEST` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`OPERATOR_REGN_REQUEST` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `STATUS_ID` INT NULL ,
  `FIRST_NM` VARCHAR(30) NOT NULL ,
  `MIDDLE_NM` VARCHAR(30) NULL ,
  `LAST_NM` VARCHAR(30) NOT NULL ,
  `OPERATOR_NM` VARCHAR(60) NULL ,
  `BUSINESS_NM` VARCHAR(60) NULL ,
  `EMAIL` VARCHAR(75) NULL ,
  `PHONE` VARCHAR(15) NULL ,
  `MOBILE` VARCHAR(15) NULL ,
  `CITY_ID` INT NULL ,
  `STATE_ID` INT NULL ,
  `COMMENTS` VARCHAR(256) NULL ,
  `CREATED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_OPERATOR_REGN_REQ_STATE`
    FOREIGN KEY (`STATE_ID` )
    REFERENCES `JKM`.`STATE_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OPERATOR_REGN_REQ_CITY`
    FOREIGN KEY (`CITY_ID` )
    REFERENCES `JKM`.`CITY_REF` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_OPERATOR_REGN_REQ_STATE_IDX` ON `JKM`.`OPERATOR_REGN_REQUEST` (`STATE_ID` ASC) ;

CREATE INDEX `FK_OPERATOR_REGN_REQ_CITY_IDX` ON `JKM`.`OPERATOR_REGN_REQUEST` (`CITY_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`OPERATOR_REGN_COMMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`OPERATOR_REGN_COMMENTS` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`OPERATOR_REGN_COMMENTS` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `OPERATOR_REGN_ID` INT NOT NULL ,
  `COMMENTS` VARCHAR(256) NOT NULL ,
  `CREATED_ON` DATETIME NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(25) NULL ,
  `MODIFIED_BY` VARCHAR(25) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_OPERATOR_REGN_REQ`
    FOREIGN KEY (`ID` )
    REFERENCES `JKM`.`OPERATOR_REGN_REQUEST` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JKM`.`VEHICLE_RATE_DETAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`VEHICLE_RATE_DETAIL` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`VEHICLE_RATE_DETAIL` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `RATE_PER_KM` DECIMAL(10,2) NULL ,
  `MIN_KM_PER_DAY` INT NULL ,
  `RATE_PER_DAY` DECIMAL(10,2) NULL ,
  `DRIVER_CHARGE_PER_DAY` DECIMAL(10,2) NULL ,
  `VEHICLE_ID` INT NULL ,
  `CREATED_BY` VARCHAR(45) NOT NULL ,
  `CREATED_ON` TIMESTAMP NOT NULL ,
  `CHANGED_BY` VARCHAR(45) NULL ,
  `CHANGED_ON` TIMESTAMP NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_VEHICLE_INFO_RATE`
    FOREIGN KEY (`VEHICLE_ID` )
    REFERENCES `JKM`.`VEHICLE_INFO` (`VEHICLE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `VEHICLE_ID_FK_IDX` ON `JKM`.`VEHICLE_RATE_DETAIL` (`VEHICLE_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`VEHICLE_SERVICE_ORIGIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`VEHICLE_SERVICE_ORIGIN` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`VEHICLE_SERVICE_ORIGIN` (
  `SERVICE_ORIGIN_ID` INT NOT NULL AUTO_INCREMENT ,
  `CITY_ID` INT NOT NULL ,
  `STATE_ID` INT NOT NULL ,
  `CREATED_ON` DATETIME NOT NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(45) NOT NULL ,
  `MODIFIED_BY` VARCHAR(45) NULL ,
  `VEHICLE_ID` INT NOT NULL ,
  PRIMARY KEY (`SERVICE_ORIGIN_ID`) ,
  CONSTRAINT `VEHICLE_SRVC_ORIG_VEHICLE_ID`
    FOREIGN KEY (`VEHICLE_ID` )
    REFERENCES `JKM`.`VEHICLE_INFO` (`VEHICLE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `VEHICLE_SRVC_ORIG_VEHICLE_ID_IDX` ON `JKM`.`VEHICLE_SERVICE_ORIGIN` (`VEHICLE_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`VEHICLE_SERVICE_DESTINATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`VEHICLE_SERVICE_DESTINATION` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`VEHICLE_SERVICE_DESTINATION` (
  `SERVICE_DEST_ID` INT NOT NULL AUTO_INCREMENT ,
  `CITY_ID` INT NOT NULL ,
  `STATE_ID` INT NOT NULL ,
  `CREATED_ON` DATETIME NOT NULL ,
  `MODIFIED_ON` DATETIME NULL ,
  `CREATED_BY` VARCHAR(45) NOT NULL ,
  `MODIFIED_BY` VARCHAR(45) NULL ,
  `VEHICLE_ID` INT NULL ,
  PRIMARY KEY (`SERVICE_DEST_ID`) ,
  CONSTRAINT `VEHICLE_SRVC_DEST_VEHICLE_ID0`
    FOREIGN KEY (`VEHICLE_ID` )
    REFERENCES `JKM`.`VEHICLE_INFO` (`VEHICLE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `VEHICLE_SRVC_DEST_VEHICLE_ID0_IDX` ON `JKM`.`VEHICLE_SERVICE_DESTINATION` (`VEHICLE_ID` ASC) ;

-- -----------------------------------------------------
-- Table `JKM`.`VEHICLE_PROMOTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`VEHICLE_PROMOTION` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`VEHICLE_PROMOTION` (
  `VEHICLE_PROMO_ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `VEHICLE_ID` INT(11) NOT NULL ,
  `PROMOTION_ID` INT(11) NOT NULL ,
  `PROMOTION_AMT` DECIMAL(10,2) NULL ,
  `PROMOTION_PCT` INT(11) NULL DEFAULT NULL ,
  `PROMO_EXP_DSC` VARCHAR(100) NULL DEFAULT NULL ,
  `CREATED_BY` VARCHAR(20) NOT NULL ,
  `CREATED_ON` DATETIME NOT NULL ,
  `CHANGED_BY` VARCHAR(20) NOT NULL ,
  `CHANGED_ON` DATETIME NOT NULL ,
  PRIMARY KEY (`VEHICLE_PROMO_ID`) ,
  CONSTRAINT `VEHICLE_PROMOTION_PROMO_ID_FK`
    FOREIGN KEY (`PROMOTION_ID` )
    REFERENCES `JKM`.`PROMOTION` (`PROMOTION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `VEHILE_PROMO_ID_VEHICLE_ID_FK`
    FOREIGN KEY (`VEHICLE_ID` )
    REFERENCES `JKM`.`VEHICLE_INFO` (`VEHICLE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `PROMO_DETAIL_PROMOTION_FK_IDX` ON `JKM`.`VEHICLE_PROMOTION` (`PROMOTION_ID` ASC) ;

CREATE INDEX `VEHILE_PROMO_ID_VEHICLE_ID_FK_IDX` ON `JKM`.`VEHICLE_PROMOTION` (`VEHICLE_ID` ASC) ;


-- -----------------------------------------------------
-- Table `JKM`.`OPERATOR_SEQ`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `JKM`.`OPERATOR_SEQ` ;

CREATE  TABLE IF NOT EXISTS `JKM`.`OPERATOR_SEQ` (
  `TYPE_ID` INT NOT NULL AUTO_INCREMENT ,
  `NEXT_VAL` BIGINT(21) NULL ,
  PRIMARY KEY (`TYPE_ID`) )
ENGINE = InnoDB;

USE `JKM` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
